# Bolig data from Dataforsyningen

## Data gathering

In [11]:
import pandas as pd
# Set pandas options to display all columns and rows
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# Set pandas option to display the full content of each column
pd.set_option('display.max_colwidth', None)

### Kommune kodes in Denmark

In [30]:
# File path to csv file
path = r"C:\Users\viet-intel\boligpriser\data\input\kommunekoder.csv"

# Load data from csv into datafram
column_names = ['navn', 'kommunekode']
kommune_df = pd.read_csv(path, sep=',', encoding='latin-1', dtype=str, header=None, names=column_names, index_col=False)

# Display the first 5 rows of the dataframe
display(kommune_df.head(5))
display(kommune_df.tail(5))

          navn kommunekode
0  Albertslund         165
1      Allerød         201
2       Assens         420
3     Ballerup         151
4      Billund         530

           navn kommunekode
93  Vordingborg         390
94          Ærø         492
95     Aabenraa         580
96      Aalborg         851
97        Århus         751

election of kommune codes in the Capital Region

In [21]:
# List of kommune names in region hovedstaden
region_hovedstad_list = ["Albertslund", "Allerød", "Ballerup", "Bornholms Regionskommune", "Brøndby", 
                "Dragør", "Egedal", "Fredensborg", "Frederiksberg", "Frederikssund", "Furesø", 
                "Gentofte", "Gladsaxe", "Glostrup", "Gribskov", "Halsnæs", "Helsingør", "Herlev", 
                "Hillerød", "Hvidovre", "Høje-Taastrup", "Hørsholm", "Ishøj", "København", "Lyngby-Taarbæk", 
                "Rudersdal", "Rødovre", "Tårnby", "Vallensbæk"]

# Creating new dataframe with only kommune names in region hovedstaden
region_hovedstad_df = kommune_df[kommune_df['navn'].isin(region_hovedstad_list)]

# Creating a list of kommune codes in region hovedstaden
region_hovedstad_kommunekode_list = region_hovedstad_df['kommunekode'].tolist()

# print(region_hovedstad_kommunekode_list)
print(region_hovedstad_kommunekode_list)

['165', '201', '151', '153', '155', '240', '210', '147', '250', '190', '157', '159', '161', '270', '217', '163', '219', '167', '169', '223', '183', '101', '230', '175', '185', '187']

### Adress collection from Dataforsyningen in one dataframe

In [25]:
import requests
import pandas as pd

test_list = ['165', '201', '151', '153', '155', '240', '210', '147', '250', '190', '157', '159', '161', '270', '217', '163', '219', '167', '169', '223', '183', '101', '230', '175', '185', '187']

# Define a function to make a api request to the danish api for housing data
def housing_data_call(kommunekode):
  
    # URL til API
    url = f"https://api.dataforsyningen.dk/adresser?kommunekode={kommunekode}&format=csv"

    # Make a GET request to the API and read the response as a DataFrame
    load_housing_adresses = pd.read_csv(url,low_memory=False, dtype={'col10': 'str'})
    return load_housing_adresses

# Empty list to store the dataframes
data_frame_list = []

# Loop through the kommune codes in region hovedstaden and make a api request for each kommune and fetch the data
for kommune in region_hovedstad_kommunekode_list:
    kommune_data = housing_data_call(kommune)
    data_frame_list.append(kommune_data)
    
# concatenate all the dataframes into one dataframe
all_kommune_df = pd.concat(data_frame_list, axis=0, ignore_index=True)

display(all_kommune_df.head())
print("lenght:", len(all_kommune_df))

,id,status,oprettet,ændret,vejkode,vejnavn,adresseringsvejnavn,husnr,etage,dør,supplerendebynavn,postnr,postnrnavn,stormodtagerpostnr,stormodtagerpostnrnavn,kommunekode,kommunenavn,ejerlavkode,ejerlavnavn,matrikelnr,esrejendomsnr,etrs89koordinat_øst,etrs89koordinat_nord,wgs84koordinat_bredde,wgs84koordinat_længde,nøjagtighed,kilde,tekniskstandard,tekstretning,ddkn_m100,ddkn_km1,ddkn_km10,adressepunktændringsdato,adgangsadresseid,adgangsadresse_status,adgangsadresse_oprettet,adgangsadresse_ændret,regionskode,regionsnavn,jordstykke_ejerlavnavn,kvhx,sognekode,sognenavn,politikredskode,politikredsnavn,retskredskode,retskredsnavn,opstillingskredskode,opstillingskredsnavn,zone,jordstykke_ejerlavkode,jordstykke_matrikelnr,jordstykke_esrejendomsnr,kvh,højde,adgangspunktid,vejpunkt_id,vejpunkt_kilde,vejpunkt_nøjagtighed,vejpunkt_tekniskstandard,vejpunkt_x,vejpunkt_y,afstemningsområdenummer,afstemningsområdenavn,brofast,supplerendebynavn_dagi_id,navngivenvej_id,menighedsrådsafstemningsområdenummer,menighedsrådsafstemningsområdenavn,vejpunkt_ændret,ikrafttrædelse,nedlagt,adgangsadresse_ikrafttrædelse,adgangsadresse_nedlagt,adgangsadresse_darstatus,darstatus,storkredsnummer,storkredsnavn,valglandsdelsbogstav,valglandsdelsnavn,landsdelsnuts3,landsdelsnavn,betegnelse
0,0a3f50a5-0d06-32b8-e044-0003ba298018,1,2000-02-05T20:51:48.000,2000-02-05T20:51:48.000,2,Abildgården,Abildgården,1,NaN,NaN,NaN,2620,Albertslund,NaN,NaN,165,Albertslund,20551.0,"Herstedvester By, Herstedvester",11z,56353.0,710829.36,6174225.40,55.667998,12.352439,A,1.0,UF,193.98,100m_61742_7108,1km_6174_710,10km_617_71,2004-11-03T00:00:00.000,0a3f507c-94c9-32b8-e044-0003ba298018,1,2000-02-05T20:51:48.000,2018-07-04T18:00:00.000,1084,Region Hovedstaden,"Herstedvester By, Herstedvester",01650002___1_______,7148,Herstedøster,1469,Københavns Vestegns Politi,1109,Retten i Glostrup,19,Taastrup,Byzone,20551.0,11z,56353.0,01650002___1,17.3,0a3f507c-94c9-32b8-e044-0003ba298018,12614483-af45-11e7-847e-066cff24d637,Ekstern,B,V0,12.352994,55.667991,5,Herstedvester Skole,1.0,NaN,4194a120-a410-4a68-a62e-e24663a93719,1.0,Herstedøster,2018-05-03T14:08:02.125,2000-02-05T20:51:48.000,NaN,2000-02-05T20:51:48.000,NaN,3,3,2,Københavns Omegn,A,Hovedstaden,DK012,Københavns omegn,"Abildgården 1, 2620 Albertslund"
1,0a3f50a5-0d07-32b8-e044-0003ba298018,1,2000-02-05T20:51:48.000,2000-02-05T20:51:48.000,2,Abildgården,Abildgården,2,NaN,NaN,NaN,2620,Albertslund,NaN,NaN,165,Albertslund,20551.0,"Herstedvester By, Herstedvester",11z,56353.0,710834.45,6174225.90,55.668000,12.352520,A,1.0,UF,193.92,100m_61742_7108,1km_6174_710,10km_617_71,2004-11-03T00:00:00.000,0a3f507c-94ca-32b8-e044-0003ba298018,1,2000-02-05T20:51:48.000,2018-07-04T18:00:00.000,1084,Region Hovedstaden,"Herstedvester By, Herstedvester",01650002___2_______,7148,Herstedøster,1469,Københavns Vestegns Politi,1109,Retten i Glostrup,19,Taastrup,Byzone,20551.0,11z,56353.0,01650002___2,17.2,0a3f507c-94ca-32b8-e044-0003ba298018,12614484-af45-11e7-847e-066cff24d637,Ekstern,B,V0,12.352994,55.667991,5,Herstedvester Skole,1.0,NaN,4194a120-a410-4a68-a62e-e24663a93719,1.0,Herstedøster,2018-05-03T14:08:02.125,2000-02-05T20:51:48.000,NaN,2000-02-05T20:51:48.000,NaN,3,3,2,Københavns Omegn,A,Hovedstaden,DK012,Københavns omegn,"Abildgården 2, 2620 Albertslund"
2,0a3f50a5-0d08-32b8-e044-0003ba298018,1,2000-02-05T20:51:48.000,2000-02-05T20:51:48.000,2,Abildgården,Abildgården,3,NaN,NaN,NaN,2620,Albertslund,NaN,NaN,165,Albertslund,20551.0,"Herstedvester By, Herstedvester",11z,56353.0,710839.50,6174226.38,55.668002,12.352600,A,1.0,UF,193.92,100m_61742_7108,1km_6174_710,10km_617_71,2004-11-03T00:00:00.000,0a3f507c-94cb-32b8-e044-0003ba298018,1,2000-02-05T20:51:48.000,2018-07-04T18:00:00.000,1084,Region Hovedstaden,"Herstedvester By, Herstedvester",01650002___3_______,7148,Herstedøster,1469,Københavns Vestegns Politi,1109,Retten i Glostrup,19,Taastrup,Byzone,20551.0,11z,56353.0,01650002___3,17.2,0a3f507c-94cb-32b8-e044-0003ba298018,12614485-af45-11e7-847e-066cff24d637,Ekstern,B,V0,12.352994,55.667991,5,Herstedvester Skole,1.0,NaN,4194a120-a410-4a68-a62e-e24663a93719,1.0,Herstedøster,2018-05-03T14:08:02.125,2000-02-05T20:51:48.000,NaN,2000-02-05T20:51:48.000,NaN,3,3,2,Københavns Omegn,A,Hovedstaden,DK012,Københavns omegn,"Abildgården 3, 2620 Albertslund"
3,0a3f50a5-0d09-32b8-e044-0003ba298018,1,2000-02-05T20:51:48.000,2000-02-05T20:51:48.000,2,Abildgården,Abildgården,4,NaN,NaN,NaN,2620,Albertslund,NaN,NaN,165,Albertslund,20551.0,"Herstedvester By, Herstedvester",11z,56353.0,710845.01,6174226.91,55.668005,12.352688,A,1.0,UF,193.92,100m_61742_7108,1km_6174_710,10km_617_71,2004-11-03T00:00:00.000,0a3f507c-94cc-32b8-e044-0003ba298018,1,2000-02-05T20:51:48.000,2018-07-04T18:00:00.000,1084,Region Hovedstaden,"Herstedvester By, Herstedvester",01650002___4_______,7148,Herstedøster,1469,Københavns Vestegns Politi,1109,Retten i Glostrup,19,Taastrup,Byzone,20551.0,11z,56353.0,01650002___4,17.2,0a3f507c-94cc-32b8-e044-0003ba298018,12614486-af45-11e7-847e-066cff24d637,Ekstern,B,V0,12.352994,55.667991,5,Herstedvester Skole,1.0,NaN,4194a120-a410-4a68-a62e-e24663a93719,1.0,Herstedøster,2018-05-03T14:08:02.125,2000-02-05T20:51:48.000,NaN,2000-02-05T20:51:48.000,NaN,3,3,2,Københavns Omegn,A,Hovedstaden,DK012,Københavns omegn,"Abildgården 4, 2620 Albertslund"
4,0a3f50a5-0d0a-32b8-e044-0003ba298018,1,2000-02-05T20:51:48.000,2000-02-05T20:51:48.000,2,Abildgården,Abildgården,5,NaN,NaN,NaN,2620,Albertslund,NaN,NaN,165,Albertslund,20551.0,"Herstedvester By, Herstedvester",11z,56353.0,710849.87,6174227.39,55.668007,12.352766,A,1.0,UF,193.98,100m_61742_7108,1km_6174_710,10km_617_71,2004-11-03T00:00:00.000,0a3f507c-94cd-32b8-e044-0003ba298018,1,2000-02-05T20:51:48.000,2018-07-04T18:00:00.000,1084,Region Hovedstaden,"Herstedvester By, Herstedvester",01650002___5_______,7148,Herstedøster,1469,Københavns Vestegns Politi,1109,Retten i Glostrup,19,Taastrup,Byzone,20551.0,11z,56353.0,01650002___5,17.3,0a3f507c-94cd-32b8-e044-0003ba298018,12614487-af45-11e7-847e-066cff24d637,Ekstern,B,V0,12.352994,55.667991,5,Herstedvester Skole,1.0,NaN,4194a120-a410-4a68-a62e-e24663a93719,1.0,Herstedøster,2018-05-03T14:08:02.125,2000-02-05T20:51:48.000,NaN,2000-02-05T20:51:48.000,NaN,3,3,2,Københavns Omegn,A,Hovedstaden,DK012,Københavns omegn,"Abildgården 5, 2620 Albertslund"

1088976

### Land (Jordstykker), data collection

In [37]:
# Define a function to make an API request to the Danish API for land data
def land_data_call(kommunekode):
  
    # URL for API
    url = f"https://api.dataforsyningen.dk/jordstykker?kommunekode={kommunekode}&format=csv"

    # Make a GET request to the API and read the response as a DataFrame
    load_land_data = pd.read_csv(url, low_memory=False)
    return load_land_data

# Empty list to store the dataframes
land_data_frame_list = []

# Loop through the kommune codes in region hovedstaden and make an API request for each kommune and fetch the data
for kommune in region_hovedstad_kommunekode_list:
    land_data = land_data_call(kommune)
    land_data_frame_list.append(land_data)
    
# concatenate all the dataframes into one dataframe
all_land_df = pd.concat(land_data_frame_list, axis=0, ignore_index=True)

display(all_land_df.head())
print("Length:", len(all_land_df))

,ændret,geo_ændret,geo_version,bbox_xmin,bbox_ymin,bbox_xmax,bbox_ymax,visueltcenter_x,visueltcenter_y,ejerlavkode,matrikelnr,kommunekode,kommunenavn,sognekode,sognenavn,regionskode,regionsnavn,retskredskode,retskredsnavn,udvidet_esrejendomsnr,esrejendomsnr,sfeejendomsnr,bfenummer,ejerlavnavn,featureid,fælleslod,moderjordstykke,registreretareal,arealberegningsmetode,vejareal,vejarealberegningsmetode,vandarealberegningsmetode
0,2023-03-29T21:04:30.316Z,2015-02-27T20:24:00.545Z,1,12.347892,55.673141,12.350759,55.674584,12.348973,55.673985,20551,11am,165,Albertslund,7148,Herstedøster,1084,Region Hovedstaden,0,NaN,1.650057e+09,57236.0,1302759,1302759.0,"Herstedvester By, Herstedvester",999291,NaN,NaN,13141,o,3160,b,ukendt
1,2023-03-29T21:04:30.316Z,2015-02-27T20:24:00.545Z,1,12.341121,55.664756,12.342912,55.665700,12.341721,55.665352,20551,12s,165,Albertslund,7155,Herstedvester,1084,Region Hovedstaden,0,NaN,1.650059e+09,58771.0,9874836,9874836.0,"Herstedvester By, Herstedvester",2647884,NaN,NaN,2393,o,1182,b,ukendt
2,2023-03-29T21:04:30.316Z,2022-07-13T21:48:52.247Z,4,12.358818,55.658780,12.362671,55.660253,12.359989,55.659484,20551,15ak,165,Albertslund,9134,Opstandelseskirkens,1084,Region Hovedstaden,0,NaN,1.650066e+09,66019.0,100095931,100095931.0,"Herstedvester By, Herstedvester",100107370,NaN,NaN,13755,o,7020,b,ukendt
3,2023-05-09T21:46:11.428Z,2023-05-09T21:46:11.428Z,5,12.360630,55.670630,12.365362,55.674651,12.363326,55.673775,20652,10a,165,Albertslund,7148,Herstedøster,1084,Region Hovedstaden,0,NaN,1.650036e+09,36042.0,2126175,2126175.0,"Herstedøster By, Herstedøster",1001576,NaN,NaN,50472,k,314,b,incl
4,2023-05-09T21:46:11.428Z,2023-05-09T21:46:11.428Z,2,12.360788,55.671963,12.362603,55.673198,12.361809,55.672650,20652,10dn,165,Albertslund,7148,Herstedøster,1084,Region Hovedstaden,0,NaN,1.650066e+09,66024.0,100174931,100174931.0,"Herstedøster By, Herstedøster",100195210,NaN,1001576.0,10584,o,780,b,ukendt

Length: 346347

In [38]:
 # URL for API
url = "https://api.dataforsyningen.dk/jordstykker?regioncode=1084&format=csv"

# Make a GET request to the API and read the response as a DataFrame
load_land_data = pd.read_csv(url, low_memory=False)

print(len(load_land_data))

2546629

In [39]:
 # URL for API
url = "https://api.dataforsyningen.dk/adresser?regioncode=1084&format=csv"

# Make a GET request to the API and read the response as a DataFrame
load_land_data = pd.read_csv(url, low_memory=False)

print(len(load_land_data))

3897491

In [48]:
url2 = "https://api.dataforsyningen.dk/bbrlight/enheder?adresseid=0a3f5097-09f2-32b8-e044-0003ba298018&format=csv"

# Make a GET request to the API and read the response as a DataFrame
load_bbr_data = pd.read_csv(url2, low_memory=False)

display(load_bbr_data.head())

Empty DataFrame
Columns: [ois_id, ois_ts, Enhed_id, ObjStatus, Nybyg, CRUD_ID, ByggeSag_id, EnhedStam_id, EnhAdr_id, Etage_id, Opgang_id, HenvEnh_id, REF_Enhed_id, ENH_ANVEND_KODE, Klassifikation, AnvKonvKilde, BOLIGTYPE_KODE, BOLIG_KONDEM, IdentOpretDato, ENH_ARL_SAML, BEBO_ARL, ENH_ERHV_ARL, KILDE_ARL_KODE, VAERELSE_ANT, TOILET_KODE, BAD_KODE, KOEKKEN_KODE, ENERGI_KODE, ENH_UDLEJ1_KODE, HusLeje, HuslejeOplysDato, AndetAreal, GodkTomBoligGL, LOVLIG_ANVEND_KODE, DispTidsbegraensetDato, SagsType, ENH_DEL_IBRUG_DATO, ENH_UDLEJ2_KODE, OFF_STOETTE_KODE, IndflytDato, GodkTomBolig, VARMEINSTAL_KODE, OPVARMNING_KODE, VARME_SUPPL_KODE, FaellesAdgArealAndel, AabenOverdaekAreal, LukOverdaekAreal, VAER_ERHV_ANT, AntVandskylToilleter, AntBadevaerelser, KomFelt1, KomFelt2, KomFelt3, KomFelt4, KomFelt5, KomFelt6, JourNr, ESDH_Ref, SikKlas, OPRET_TS, AENDR_TS, Aendr_Funk, Ophoert_ts, Gyldighedsdato, opgang_ois_id, opgang_ois_ts, opgang_Opgang_id, opgang_AdgAdr_id, opgang_ObjStatus, opgang_NyByg, opgang_Crud_id, opgang_ByggeSag_id, opgang_OpgStam_id, opgang_Bygning_id, opgang_Elevator, opgang_DataFelt1, opgang_DataFelt2, opgang_DataFelt3, opgang_SagsType, opgang_KomFelt1, opgang_KomFelt2, opgang_KomFelt3, opgang_KomFelt4, opgang_KomFelt5, opgang_KomFelt6, opgang_JourNr, opgang_ESDH_Ref, opgang_SikKlas, opgang_OPRET_TS, opgang_AENDR_TS, opgang_Aendr_Funk, opgang_Ophoert_ts, opgang_Gyldighedsdato, bygning_ois_id, bygning_ois_ts, bygning_Bygning_id, bygning_Bygningsnr, bygning_ObjStatus, bygning_NyByg, bygning_Crud_id, ...]
Index: []

In [84]:
import requests
import pandas as pd

# Set the API URL
api_url = "https://services.datafordeler.dk/BBR/BBRPublic/1/rest/enhed"

# Function to fetch data
def fetch_data(kommunekode):
    # Set the parameters
    params = {
        "username": "ANLVUSSNAP",
        "password": "Essvietcc567!",
        "Format": "JSON",
        "Kommunekode": kommunekode,
        "pagesize": 9999999,  # Specify the maximum page size
        "page": 1  # Request the first page
    }

    # Fetch data from the API
    response = requests.get(api_url, params=params)

    # Check the status code and proceed with processing the response
    if response.status_code == 200:
        try:
            data = response.json()
            df = pd.DataFrame(data)
            return df

        except ValueError as e:
            print(f"Failed to decode JSON for kommunekode {kommunekode}.")
            return None

    else:
        print(f"Failed to fetch data for kommunekode {kommunekode} from the API. Status code: {response.status_code}")
        return None

# List of kommunekode values to iterate over
kommunekode_list = ['0165', '0201', '0151', '0153', '0155', '0240', '0210', '0147', '0250', '0190', '0157', '0159', '0161', '0270', '0217', '0163', '0219', '0167', '0169', '0223', '0183', '0101', '0230', '0175', '0185', '0187']


# Initialize an empty list to store the DataFrames
dataframes = []

# Fetch data for each kommunekode
for kommunekode in kommunekode_list:
    df = fetch_data(kommunekode)
    if df is not None:
        dataframes.append(df)

# Concatenate all the dataframes in the list
final_df = pd.concat(dataframes)

# Display the first few rows and the total length of the final DataFrame
display(final_df.head())
print("Length:", len(final_df))

,datafordelerOpdateringstid,adresseIdentificerer,enh020EnhedensAnvendelse,enh023Boligtype,enh026EnhedensSamledeAreal,enh027ArealTilBeboelse,enh030KildeTilEnhedensArealer,enh031AntalVærelser,enh032Toiletforhold,enh033Badeforhold,enh034Køkkenforhold,enh045Udlejningsforhold,enh048GodkendtTomBolig,enh065AntalVandskylledeToiletter,enh066AntalBadeværelser,enh071AdresseFunktion,etage,forretningshændelse,forretningsområde,forretningsproces,id_lokalId,id_namespace,kommunekode,opgang,registreringFra,registreringsaktør,status,virkningFra,virkningsaktør,bygning,enh024KondemneretBoligenhed,enh067Støjisolering,enh025OprettelsesdatoForEnhedensIdentifikation,enh035Energiforsyning,ejerlejlighedList,enh028ArealTilErhverv,enh046OffentligStøtte,enh063AntalVærelserTilErhverv,enh101Gyldighedsdato,enh060EnhedensAndelFællesAdgangsareal,enh070ÅbenAltanTagterrasseAreal,enh051Varmeinstallation,enh068FlexboligTilladelsesart,enh127FysiskArealTilBeboelse,fordelingsarealList,enh053SupplerendeVarme,enh062ArealAfLukketOverdækningUdestue,enh052Opvarmningsmiddel,enh039AndetAreal,enh047IndflytningDato,enh041LovligAnvendelse,enh044DatoForDelvisIbrugtagningsTilladelse,enh042DatoForTidsbegrænsetDispensation,enh008UUIDTilModerlejlighed,enh128FysiskArealTilErhverv
0,2021-04-03T17:52:53.115133+02:00,0a3f50a5-3c61-32b8-e044-0003ba298018,130,1,106.0,106.0,1,4.0,T,V,E,1,0,1.0,1.0,0,c0034a30-e3a9-47db-8df8-fc09ac978e06,Enhed,54.15.05.05,0,000146fc-eb6d-449e-9ecd-a90bea4b6963,http://data.gov.dk/bbr/enhed,0165,01e09215-259d-4a33-a16c-545e8300059c,2018-09-14T19:31:21.793333+02:00,BBR,6,2018-09-14T19:31:21.793333+02:00,BBR,643e4ffe-60ce-40d4-aec3-7f8e93709897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-02-27T15:07:49.672495+01:00,0a3f50a5-3b93-32b8-e044-0003ba298018,150,3,29.0,29.0,1,1.0,T,V,F,1,0,1.0,1.0,1,be4164f9-4c7c-4a62-8ca1-139a383656af,Enhed,54.15.05.05,4,00019635-4426-4b7f-9afc-9623facdc80f,http://data.gov.dk/bbr/enhed,0165,b46abcef-2997-4b1f-b108-05c2e7125a30,2023-02-27T15:07:24.284866+01:00,BBR,10,2023-02-27T15:07:24.284866+01:00,Registerfører,c5b3d260-7dd6-4179-a43b-2b267354383b,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-02-27T15:20:40.813256+01:00,0a3f50a5-3b5e-32b8-e044-0003ba298018,150,3,29.0,29.0,1,1.0,T,V,F,1,0,1.0,1.0,1,1aca0cd2-6782-436f-ada9-154aec8f4364,Enhed,54.15.05.05,4,0004658e-4916-4ef6-bc67-0973bde1ba24,http://data.gov.dk/bbr/enhed,0165,0dd607ca-5d1b-474e-8f70-63d4507948a6,2023-02-27T15:20:17.927211+01:00,BBR,10,2023-02-27T15:20:17.927211+01:00,Registerfører,f3cd9fa9-407b-47d2-8026-c99922b48038,0,1989.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-04-03T21:48:30.775694+02:00,0a3f50a5-3946-32b8-e044-0003ba298018,130,1,108.0,108.0,2,4.0,T,V,E,2,0,2.0,1.0,0,dc49fa42-8d11-4a6d-b32c-9041bbeff496,Enhed,54.15.05.05,0,000e98a8-3e86-4256-bddd-7a5d3ee1ba1c,http://data.gov.dk/bbr/enhed,0165,9c3c77b2-6489-4ad9-b6fe-17ec9cd35579,2020-04-04T10:58:46.707230+02:00,BBR,6,2020-04-04T10:58:46.707230+02:00,BBR,010d260b-bd22-4693-85e4-064afb8564ae,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-04-03T16:36:44.354267+02:00,78bb4ea7-90a4-4914-e044-00144f3ead67,130,1,68.0,68.0,2,1.0,T,V,E,1,0,1.0,1.0,0,8ed6f4ca-cb93-4126-823f-e584d334e6b5,Enhed,54.15.05.05,0,00104c36-9e4c-4d70-81de-41f9cec1955e,http://data.gov.dk/bbr/enhed,0165,0e586f8a-66d1-4548-8a23-cc1d5cefee53,2018-09-14T19:15:16.456667+02:00,BBR,6,2018-09-14T19:15:16.456667+02:00,BBR,29bb3da3-a20b-42ba-82a4-d7f80e2edf1f,0,NaN,2006-06-15T00:00:00.000000+02:00,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Length: 1165203

In [85]:
# Save the DataFrame to a pickle file
final_df.to_pickle(r"C:\Users\viet-intel\boligpriser\data\output\bbr_enhed.pkl")